services:
  # ======================================
  # DB for order-service
  # ======================================
  postgres:
    restart: unless-stopped
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/data/postgres
    networks:
      - postgres-network
    environment:
      POSTGRES_USER: cottin
      POSTGRES_PASSWORD: password
      POSTGRES_SERVERNAME: cottin
      PGDATA: /data/postgres
  # ======================================
  # Graphic interface for order-service
  # ======================================
  pgadmin:
    depends_on:
      - postgres
    restart: unless-stopped
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "5050:80"
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      - postgres-network
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
  # ======================================
  # DB for product-service
  # ======================================
  mongodb:
    restart: unless-stopped
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ~/apps/mongo:/var/lib/mongodb/data
    networks:
      - mongo-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: cottin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: product-service
  # ======================================
  # Graphic interface for product-service
  # ======================================
  mongo-express:
    depends_on:
      - mongodb
    restart: unless-stopped
    image: mongo-express
    container_name: mongo-express
    ports:
      - "6082:8081"
    volumes:
      - ~/apps/mongo-express:/var/lib/mongo-express/data
    networks:
      - mongo-network
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: cottin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_BASICAUTH_USERNAME: cottin
      ME_CONFIG_BASICAUTH_PASSWORD: password
  # ======================================
  # Keycloack Server
  # ======================================
  keycloak:
    restart: unless-stopped
    image: quay.io/keycloak/keycloak:18.0.0
    container_name: keycloack
    ports:
      - "8181:8080"
    environment:
      KEYCLOAK_ADMIN: cottin
      KEYCLOAK_ADMIN_PASSWORD: password
      KEYCLOAK_LOGLEVEL: INFO
      ROOT_LOGLEVEL: INFO
    command:
      - start-dev
# ======================================
# Networks configuration
# ======================================
networks:
  postgres-network:
    driver: bridge
  mongo-network:
    driver: bridge
# ======================================
# Volumes configuration
# ======================================
volumes:
  postgres:
  pgadmin:
  mongodb:
  mongo-express: