server:
  port: 8761

spring:
  application:
    name: api-gateway
  zipkin.base-url: http://localhost:9411
  sleuth.sampler.probability: 1.0

# Spring Cloud Eureka Server properties
eureka:
  username: ${EUREKA_USERNAME:eureka}
  password: ${EUREKA_PASSWORD:password}
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false