server:
  port: 8080
spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: mongodb://cottin:password@localhost:27017/product-service?authSource=admin
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka