server:
  port: 8081 # if port: 0 --> listen on a random free port

spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: mongodb://cottin:password@localhost:27017/product-service?authSource=admin
  zipkin.base-url: http://localhost:9411
  sleuth.sampler.probability: 1.0

# Spring Cloud Eureka Server properties
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka